# Generated by Django 3.0.7 on 2020-08-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='quantity',
            field=models.IntegerField(default=434),
        ),
    ]
