# Generated by Django 3.0.7 on 2020-08-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_modification_conventional_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='conventional_designation',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='quantity',
        ),
    ]
