# Generated by Django 3.0.7 on 2020-09-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200907_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='meta_keywords',
        ),
    ]
