# Generated by Django 3.1 on 2020-09-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200907_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
    ]
