# Generated by Django 3.0.7 on 2020-09-12 20:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200909_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description group'),
        ),
        migrations.AlterField(
            model_name='product',
            name='href_title',
            field=models.CharField(max_length=250, verbose_name='title group'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=123, upload_to='mechanisms_preview', verbose_name='Изображение для ссылки'),
            preserve_default=False,
        ),
    ]
