# Generated by Django 3.0.7 on 2020-09-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200912_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDocs',
        ),
    ]
