# Generated by Django 3.0.7 on 2020-09-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20200917_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdocs',
            name='name',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
