# Generated by Django 3.0.7 on 2020-09-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_productdocs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='key_filter',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
