# Generated by Django 3.0.7 on 2020-09-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_documentation_key_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='doc_group',
        ),
    ]
