# Generated by Django 3.0.7 on 2020-10-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20201007_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentation',
            options={'ordering': ['name']},
        ),
    ]
