# Generated by Django 3.0.7 on 2020-11-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20201007_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='dark_banner',
            field=models.BooleanField(default=True),
        ),
    ]
