# Generated by Django 3.1.1 on 2020-11-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_group_dark_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentation',
            options={'ordering': ['key_sort']},
        ),
    ]
