# Generated by Django 3.0.7 on 2020-11-28 10:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20201112_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sensor',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'М'), (2, 'У'), (3, 'Р'), (4, 'И'), (5, 'БЦА')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
