# Generated by Django 3.1.1 on 2020-11-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20201112_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
