# Generated by Django 3.0.7 on 2020-11-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20201128_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sensor',
            new_name='sensors',
        ),
    ]
