# Generated by Django 3.0.7 on 2020-11-28 11:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20201128_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('М', 'М'), ('У', 'У'), ('Р', 'Р'), ('И', 'И'), ('БЦА', 'БЦА')], max_length=250)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='sensors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('М', 'М'), ('У', 'У'), ('Р', 'Р'), ('И', 'И'), ('БЦА', 'БЦА')], max_length=100, null=True),
        ),
    ]
