# Generated by Django 3.1.1 on 2020-11-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20201128_1155'),
        ('mainapp', '0022_productimage_show'),
    ]

    operations = [
    ]
