# Generated by Django 3.0.7 on 2020-11-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_merge_20201128_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensors',
            options={},
        ),
    ]
