# Generated by Django 3.0.7 on 2020-11-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20201128_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='name',
            new_name='character',
        ),
    ]
