# Generated by Django 3.1.1 on 2020-12-10 15:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20201128_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sensors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('М', 'М'), ('У', 'У'), ('Р', 'Р'), ('И', 'И'), ('БЦА', 'БЦА'), ('БКП', 'БКП'), ('ЕД', 'ЕД'), ('БУМ', 'БУМ'), ('ЕДМ', 'ЕДМ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='character',
            field=models.CharField(choices=[('М', 'М'), ('У', 'У'), ('Р', 'Р'), ('И', 'И'), ('БЦА', 'БЦА'), ('БКП', 'БКП'), ('ЕД', 'ЕД'), ('БУМ', 'БУМ'), ('ЕДМ', 'ЕДМ')], max_length=250),
        ),
    ]
