# Generated by Django 3.1.1 on 2020-12-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20201210_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
