# Generated by Django 3.0.7 on 2020-12-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_product_meta_keywords'),
        ('mainapp', '0030_auto_20201220_1810'),
    ]

    operations = [
    ]
