# Generated by Django 3.1.4 on 2020-12-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_merge_20201220_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('picture', models.ImageField(null=True, upload_to='certificates/picture')),
                ('file', models.FileField(null=True, upload_to='certificates/file')),
            ],
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='file',
            new_name='icon_file',
        ),
    ]
