# Generated by Django 3.1.4 on 2021-01-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20201223_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='document_category',
            field=models.CharField(choices=[('Общепром', 'Общепром'), ('Взрыв', 'Взрыв'), ('Датчики и контроллеры', 'Датчики и контроллеры'), ('Пусковые и управляющие', 'Пусковые и управляющие'), ('Шлагбаумы', 'Шлагбаумы')], max_length=255, null=True),
        ),
    ]
