# Generated by Django 3.1.4 on 2021-01-13 22:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_documentation_document_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='groups_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
