# Generated by Django 3.1.1 on 2021-01-17 18:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_group_groups_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groups_content',
            field=tinymce.models.HTMLField(blank=True, help_text='Блок информации показывается на каждой странице группы (для обобщенной информации)', null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='img',
            field=models.ImageField(blank=True, help_text='размер 925x625, ppi 300 и вес не более 60кб', null=True, upload_to='main_page'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='description',
            field=models.TextField(max_length=700),
        ),
    ]
