# Generated by Django 3.1.1 on 2021-01-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20210117_1835'),
        ('mainapp', '0036_auto_20210117_1903'),
    ]

    operations = [
    ]
