# Generated by Django 3.1.1 on 2021-01-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_merge_20210124_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Sensor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
    ]
