# Generated by Django 3.1.7 on 2021-03-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_auto_20210327_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='icon',
            new_name='img',
        ),
    ]
