# Generated by Django 3.1.1 on 2021-03-31 17:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_auto_20210327_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
