# Generated by Django 3.1.1 on 2021-03-31 18:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_group_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='position',
            field=models.IntegerField(unique=True, verbose_name='Позиция на странице каталога'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Превью. Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='h1_mod',
            field=models.CharField(max_length=250, verbose_name='Заголовок всех модификаций'),
        ),
        migrations.AlterField(
            model_name='product',
            name='href_title',
            field=models.CharField(max_length=250, verbose_name='Превью. Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mod_table',
            field=tinymce.models.HTMLField(help_text="Нужно идентификатора обязательно. id = 'MOD' "),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Страница группы. Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_product',
            field=models.SlugField(help_text='Например, "160" или "6_3"', verbose_name='url'),
        ),
    ]
