# Generated by Django 3.1.1 on 2021-03-31 18:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_auto_20210331_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=tinymce.models.HTMLField(help_text='синие подзаголовки - H4. Черные подзаговолки просто жирным'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='mechanisms_preview', verbose_name='Превью. Картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mod_table',
            field=tinymce.models.HTMLField(help_text="Нужно добавить id | <table id = 'MOD'>  ", verbose_name='Таблица модификаций'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать?'),
        ),
    ]
