# Generated by Django 3.1.1 on 2021-03-31 18:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_auto_20210331_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mod_table',
            field=tinymce.models.HTMLField(help_text="Нужно добавить id таблице. <table id = 'MOD'> "),
        ),
    ]
