# Generated by Django 3.1.1 on 2021-04-08 18:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20210404_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('-first',)},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='show',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='first',
            field=models.BooleanField(default=False),
        ),
    ]
